#!/usr/bin/env zsh
emulate -L zsh
setopt nounset err_exit
#setopt xtrace

if ! (( $+TRY_HELPERS_HOME )); then
	echo "You must set TRY_HELPERS_HOME to the directory of the checked out try-helpers repository." >&2
	exit 1
fi

git init "$@"
zmodload -F zsh/files +b:ln
ln -s "$TRY_HELPERS_HOME"/post-update .git/hooks
git config receive.denyCurrentBranch ignore
