#!/usr/bin/env zsh
emulate -L zsh
setopt nounset err_exit
#setopt xtrace

readonly TRY_HELPERS_HOME="$HOME/Sources/try-helpers"

git init "$@"
zmodload -F zsh/files +b:ln
ln -s "$TRY_HELPERS_HOME"/post-update .git/hooks
git config receive.denyCurrentBranch ignore
