#!/usr/bin/env zsh
emulate -L zsh
setopt err_exit nounset
#setopt xtrace

zmodload -F zsh/zutil +b:zparseopts
typeset -a tryopts
zparseopts -D -K -E -a tryopts -batch=batch q

function try {
	readonly TRY="/usr/local/dcs/bin/try"
	if (( $+batch )); then
		{
			setopt noxtrace
			while true; do
				echo -n '\n'
			done
		} < /dev/null | exec "$TRY" "$@"
	else
		exec "$TRY" "$@"
	fi
}

typeset -r SPECFILE="TRYSPEC"

if [[ ! -f "$SPECFILE" || $# -ne 0 ]]; then
	exec try "${tryopts[@]}" "$@"
fi

source "$SPECFILE"

try "${tryopts[@]}" "$INSTRUCTOR" "$PROJECT" "${FILES[@]}"

# vim:ft=zsh
